### ISSUE TITLE
Program the Events page

### ISSUE THREAD

**Issue by nickworks** [nickworks/megaworks#12]
Program out the front-end (HTML / CSS) of the Events page.
Refer to the HD wireframe (if one exists).

**Comment by Nate41223** [comment]
a rough draft for the events page is made and pushed up through git kraken. However, I don't feel like my coding was the most efficient and my design feels a little dull. Suggestions for improvement on both would be much appreciated.

**Comment by Nate41223** [comment]
merged with master
