### ISSUE TITLE
Program the Signup page

### ISSUE THREAD

**Issue by nickworks** [nickworks/megaworks#18]
Program out the front-end (HTML / CSS) of the Signup page.
Refer to the HD wireframe (if one exists).

**Comment by SweaterWeather** [comment]
- Space needed between "Already have an account?" and "Login!"

- Phrasing "Post a Picture!" is unclear, it should probably say something to the effect of "Upload a Profile Picture!"

- Take a second look at the vertical spacing of the elements, some parts are mashed up very close together.
