### ISSUE TITLE
Wireframe the Events page

### ISSUE THREAD

**Issue by nickworks** [nickworks/megaworks#2]
This page should contain an embedded events calendar. It would probably be best if it looked like a calendar. Visitors should be able to click on an event to go to a page with more info (the Event page).

**Comment by nickworks** [comment]
Use the examples in the Google Drive. When you're finished, drop your wireframe into Google Drive as "**_events (HD) v1.psd_**".

**Comment by Nate41223** [comment]
Wireframe of the events page is made and uploaded to the drive under "**_events (HD) v1.psd_**".
